In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

### 1) Normalization

In [3]:
data=np.array([1.0,12.4,3.9,10.4])
data

array([ 1. , 12.4,  3.9, 10.4])

### For [0,1]

In [4]:
#X-Xmin / Xmax-Xmin
norm=(data-np.min(data))/(np.max(data)-np.min(data))
norm

array([0.        , 1.        , 0.25438596, 0.8245614 ])

### For [a,b]

In [5]:
a=5
b=10
norm=a+((data-np.min(data))* (b-a)/(np.max(data)-np.min(data)))
norm

array([ 5.        , 10.        ,  6.27192982,  9.12280702])

### MinMaxScaler for normalization of Data in range  between 0 and 1

In [ ]:
#fit 
#transform
#inverse transform
#fit_transform

In [10]:
mm=MinMaxScaler()
mm.fit(data.reshape(-1,1))
norm=mm.transform(data.reshape(-1,1))
norm

array([[0.        ],
       [1.        ],
       [0.25438596],
       [0.8245614 ]])

In [12]:
mm.inverse_transform([[0.25438596]]) #=> 3.9

array([[3.89999994]])

In [13]:
mm.fit_transform(data.reshape(-1,1))

array([[0.        ],
       [1.        ],
       [0.25438596],
       [0.8245614 ]])

### MinMaxScaler for normalization of Data in range  between a and b

In [15]:
a=5
b=10
mm=MinMaxScaler(feature_range=(a,b))
mm.fit(data.reshape(-1,1))
norm=mm.transform(data.reshape(-1,1))
norm

array([[ 5.        ],
       [10.        ],
       [ 6.27192982],
       [ 9.12280702]])

In [16]:
norm=mm.fit_transform(data.reshape(-1,1))
norm

array([[ 5.        ],
       [10.        ],
       [ 6.27192982],
       [ 9.12280702]])

### 2) Standardization

In [17]:
data

array([ 1. , 12.4,  3.9, 10.4])

In [19]:
#scale_data =X -mean / std
scaled_data=(data-np.mean(data))/np.std(data)
scaled_data

array([-1.27554   ,  1.17866354, -0.65122506,  0.74810152])

In [20]:
## mean of scaled Data
np.mean(scaled_data)
#-1.11022 x 10^ -16

-1.1102230246251565e-16

In [21]:
np.std(scaled_data)

0.9999999999999998

### StandardScaler z-scale normalization

In [ ]:
#fit
#transform
#inverse_transform
#fit_transform

In [25]:
sc=StandardScaler()
data=data.reshape(-1,1)
sc.fit(data)
sc.transform(data)

array([[-1.27554   ],
       [ 1.17866354],
       [-0.65122506],
       [ 0.74810152]])

In [26]:
sc.inverse_transform([[-0.65122506]])

array([[3.90000001]])

In [27]:
sc.fit_transform(data)

array([[-1.27554   ],
       [ 1.17866354],
       [-0.65122506],
       [ 0.74810152]])

In [48]:
scaled_data.std()

Density    1.00199
bodyfat    1.00199
Age        1.00199
Weight     1.00199
Height     1.00199
Neck       1.00199
Chest      1.00199
Abdomen    1.00199
Hip        1.00199
Thigh      1.00199
Knee       1.00199
Ankle      1.00199
Biceps     1.00199
Forearm    1.00199
Wrist      1.00199
dtype: float64