In [1]:
import numpy as np
import pandas as pd

In [2]:
df=np.genfromtxt('.//Data//Bodyfat.csv',delimiter=',')

In [3]:
df

array([[    nan,     nan,     nan, ...,     nan,     nan,     nan],
       [ 1.0708, 12.3   , 23.    , ..., 32.    , 27.4   , 17.1   ],
       [ 1.0853,  6.1   , 22.    , ..., 30.5   , 28.9   , 18.2   ],
       ...,
       [ 1.0328, 29.3   , 72.    , ..., 31.3   , 27.2   , 18.    ],
       [ 1.0399, 26.    , 72.    , ..., 30.5   , 29.4   , 19.8   ],
       [ 1.0271, 31.9   , 74.    , ..., 33.7   , 30.    , 20.9   ]])

## Creating Array

In [4]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr=np.array([(1,2,3),(4,5,6),(7,8,9)])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros(3)
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [9]:
np.arange(0,100,6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [10]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.random.rand(4,5)

array([[0.11425529, 0.83519248, 0.93694599, 0.02513744, 0.45742931],
       [0.85540348, 0.84777336, 0.13351103, 0.38100323, 0.14172124],
       [0.8990898 , 0.5246397 , 0.81151771, 0.96548242, 0.10618221],
       [0.10679154, 0.72644734, 0.76973024, 0.57635092, 0.44629732]])

In [12]:
np.random.randint(5,size=(4,5)) # random int from 0 to 4

array([[1, 0, 3, 3, 1],
       [2, 0, 0, 0, 1],
       [1, 0, 2, 3, 4],
       [3, 1, 0, 4, 2]])

## Inspecting Properties

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.size

9

In [15]:
arr.shape

(3, 3)

In [16]:
arr.dtype

dtype('int32')

In [17]:
arr=arr.astype(float)   # to convert dtype to float,str,int
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [18]:
arr.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [19]:
arr=np.array([(5,3,6),(5,2,4),(5,6,9)])
arr.sort()      # sorts rows of array
arr

array([[3, 5, 6],
       [2, 4, 5],
       [5, 6, 9]])

In [20]:
arr.sort(axis=0)
arr

array([[2, 4, 5],
       [3, 5, 6],
       [5, 6, 9]])

In [21]:
arr.flatten()    #to convert in one dimension

array([2, 4, 5, 3, 5, 6, 5, 6, 9])

In [22]:
arr.T

array([[2, 3, 5],
       [4, 5, 6],
       [5, 6, 9]])

## Adding and Deleting elements

In [23]:
arr2=np.array([(1,2,3),(4,5,6),(7,8,9)])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.append(arr,arr2)

array([2, 4, 5, 3, 5, 6, 5, 6, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.delete(arr,2,axis=1)

array([[2, 4],
       [3, 5],
       [5, 6]])

In [26]:
np.concatenate((arr,arr2),axis=1)

array([[2, 4, 5, 1, 2, 3],
       [3, 5, 6, 4, 5, 6],
       [5, 6, 9, 7, 8, 9]])

In [27]:
np.split(arr,3)

[array([[2, 4, 5]]), array([[3, 5, 6]]), array([[5, 6, 9]])]

In [28]:
np.hsplit(arr,3)

[array([[2],
        [3],
        [5]]),
 array([[4],
        [5],
        [6]]),
 array([[5],
        [6],
        [9]])]

## Indexing / Slicing / Subsetting

In [31]:
arr[2,1]

6

In [34]:
arr[2,1]=7
arr

array([[2, 4, 5],
       [3, 5, 6],
       [5, 7, 9]])

In [38]:
arr[0:2,0:2]

array([[2, 4],
       [3, 5]])

In [39]:
arr[:2]

array([[2, 4, 5],
       [3, 5, 6]])

In [40]:
arr[:,1]

array([4, 5, 7])

In [44]:
arr<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [45]:
arr[arr<5]

array([2, 4, 3])

## Scalar Math

In [46]:
np.add(arr,2)  #  subtract,multiply,divide,power

array([[ 4,  6,  7],
       [ 5,  7,  8],
       [ 7,  9, 11]])

## Vector Math

In [47]:
np.add(arr,arr2)  # subtract,multiply,divide,power,sqrt,log,abs

array([[ 3,  6,  8],
       [ 7, 10, 12],
       [12, 15, 18]])

## Statistics

In [50]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr.sum()

46

In [52]:
np.mean(arr2,axis=0)

array([4., 5., 6.])

In [60]:
np.var(arr2,axis=0)

array([6., 6., 6.])

In [63]:
np.std(arr2,axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [65]:
arr2.max(axis=0)

array([7, 8, 9])